version: "3.8"

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.role == mongo

  app:
    build: .
    image: todo:latest         # local tag
    environment:
      MONGO_DB_URI: mongodb://admin:password@mongo:27017
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.role == app

networks:
  app-network:
    driver: overlay

volumes:
  mongo-data:
