services:
  mongo:
    image: mongo
    container_name: adb-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data
volumes:
  redis-data:
  mongo-data:
  neo4j-data: