name: owasp

permissions:
  contents: read
  issues: write
  pull-requests: write
  actions: read

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/dast.yml
  pull_request:
    branches: [ "master" ]
    paths:
    - .github/workflows/dast.yml
  schedule:
    - cron: '0 0 * * *'

jobs:
  owasp:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "http://localhost:3000"
          artifact_name: zap_scan
