name: CI/CD

permissions:
  contents: read
  pull-requests: read
  issues: write

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths-ignore:
      - .github/workflows/sonarcloud.yml
      - .github/workflows/semgrep.yml
      - .github/workflows/dast.yml
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - .github/workflows/sonarcloud.yml
      - .github/workflows/semgrep.yml
      - .github/workflows/dast.yml


jobs:
  build:
    name: build image
    runs-on: ubuntu-sonarcloud

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push full-stack image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/todo:latest
            ghcr.io/${{ github.repository_owner }}/todo:${{ github.sha }}

  deploy:
    name: deploy
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy stack to Swarm
        run: |
          docker stack deploy \
            -c docker-stack.yml \
            todo_stack