name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Build & load full-stack image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          load: true            # loads into local Docker on worker-2
          tags: todo:latest

  deploy:
    name: Deploy from manager
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy stack to Swarm
        run: |
          docker stack deploy \
            -c docker-stack.yml \
            todo_stack
