name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: [ self-hosted, linux ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & load fullstack image locally
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false       # do not push to any registry
          load: true        # load into local Docker
          tags: todo:latest

      - name: Deploy stack to Docker Swarm
        run: |
          docker stack deploy \
            -c docker-stack.yml \
            todo_stack
