name: semgrep

on:
  workflow_dispatch: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: 0 0 * * *

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - run: semgrep ci
