name: semgrep

permissions:
  contents: read
  issues: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/semgrep.yml
  pull_request:
    branches: [ "master" ]
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: 0 0 * * *

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - name: Run Semgrep and output findings
      run: semgrep ci --json > semgrep-findings.json
    - name: Create GitHub Issue from Semgrep findings
      if: always()
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: "Semgrep Findings"
        content-filepath: semgrep-findings.json
        labels: semgrep, security
