name: semgrep

permissions:
  contents: read
  issues: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/semgrep.yml
  pull_request:
    branches: [ "master" ]
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: 0 0 * * *

jobs:
  semgrep:
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep

    steps:
    - uses: actions/checkout@v4
    - name: Run Semgrep and output findings
      run: semgrep ci --exclude test --exclude '**/*.test.*' --exclude '**/*.spec.*' --json > semgrep-findings.json
    - name: Convert Semgrep findings to markdown
      run: |
        echo "# Semgrep Findings\n" > semgrep-findings.md
        count=$(jq '[.results[] | select(.extra.severity == "CRITICAL" or .extra.severity == "HIGH")] | length' semgrep-findings.json)
        if [ "$count" -eq 0 ]; then
          echo "No Semgrep findings." >> semgrep-findings.md
        else
          jq -r '.results[] | select(.extra.severity == "CRITICAL" or .extra.severity == "HIGH") | "- [\(.extra.severity)] \(.check_id): \(.path):\(.start.line) - \(.extra.message // .check_id)"' semgrep-findings.json >> semgrep-findings.md
        fi
    - name: Create GitHub Issue from Semgrep findings
      if: always()
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: "Semgrep Findings"
        content-filepath: semgrep-findings.md
        labels: semgrep, security
